### ISSUE TITLE
证书错误是因为gradle或者idea的原因？

### ISSUE THREAD

**Issue by linmii** [wuyr/GoogleLibraryVersionQuerier#35]
按`Ctrl+Alt+Q`查询版本，提示证书错误提示，点击ok，再按快捷键查询就一直提示“找不到依赖库”，但是直接在.gradle文件中输入依赖关键字有列表展示。

```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
```

![image](https://user-images.githubusercontent.com/17309471/93023092-301f5400-f61f-11ea-955c-a9df0eb7ea54.png)

![image](https://user-images.githubusercontent.com/17309471/93023107-3f9e9d00-f61f-11ea-9f87-e67d12e46e12.png)

![image](https://user-images.githubusercontent.com/17309471/93023158-9ad08f80-f61f-11ea-9a8c-756111bd608f.png)

**Comment by wuyr** [comment]
惨了惨了，<https://maven.aliyun.com/mvn/view> 阿里云的maven镜像，现在查不到仓库详情了，直接在网站上点进去，都提示系统出错了。。。。

**Comment by linmii** [comment]
> 惨了惨了，https://maven.aliyun.com/mvn/view 阿里云的maven镜像，现在查不到仓库详情了，直接在网站上点进去，都提示系统出错了。。。。

我能进去……

![image](https://user-images.githubusercontent.com/17309471/93050559-aa8abb00-f695-11ea-8bde-58bb0cf5faa5.png)

**Comment by wuyr** [comment]
> > 惨了惨了，https://maven.aliyun.com/mvn/view 阿里云的maven镜像，现在查不到仓库详情了，直接在网站上点进去，都提示系统出错了。。。。
> 
> 我能进去……
> 
> ![image](https://user-images.githubusercontent.com/17309471/93050559-aa8abb00-f695-11ea-8bde-58bb0cf5faa5.png)

进去是能进去，你随便点一个仓库右边的 【仓库详情】，然后试试展开弹出框左边的tree视图

**Comment by linmii** [comment]
> > > 惨了惨了，https://maven.aliyun.com/mvn/view 阿里云的maven镜像，现在查不到仓库详情了，直接在网站上点进去，都提示系统出错了。。。。
> > 
> > 
> > 我能进去……
> > ![image](https://user-images.githubusercontent.com/17309471/93050559-aa8abb00-f695-11ea-8bde-58bb0cf5faa5.png)
> 
> 进去是能进去，你随便点一个仓库右边的 【仓库详情】，然后试试展开弹出框左边的tree视图

果然，提示错误，估计阿里都还不知道吧，也没有反馈入口……

**Comment by linmii** [comment]
> > > 惨了惨了，https://maven.aliyun.com/mvn/view 阿里云的maven镜像，现在查不到仓库详情了，直接在网站上点进去，都提示系统出错了。。。。
> > 
> > 
> > 我能进去……
> > ![image](https://user-images.githubusercontent.com/17309471/93050559-aa8abb00-f695-11ea-8bde-58bb0cf5faa5.png)
> 
> 进去是能进去，你随便点一个仓库右边的 【仓库详情】，然后试试展开弹出框左边的tree视图

是关闭了这个入口吗？响应给的是无权限访问

![image](https://user-images.githubusercontent.com/17309471/93054407-db6dee80-f69b-11ea-82e0-ef7b0c1e07e4.png)

**Comment by wuyr** [comment]
哭唧唧，不知道是临时关闭还是永久关闭

**Comment by wuyr** [comment]
如果是接口有更改的话，应该会提供新的接口的，但现在它网站上的详情树也还没更新

**Comment by wuyr** [comment]
刚刚发现阿里云已经修复这个问题了，现在接口可以正常访问

**Comment by linmii** [comment]
> 刚刚发现阿里云已经修复这个问题了，现在接口可以正常访问

收到！

另外请问下，kotlin项目的`*.gradle.kts`这个插件不支持是吧？

**Comment by wuyr** [comment]
现在只支持.gradle后缀的文件，kts以后会添加支持
