### ISSUE TITLE
查找依赖库历史版本时出错

### ISSUE THREAD

**Issue by 880634** [wuyr/GoogleLibraryVersionQuerier#48]
大大，现在插件直接用不了，我这边排查了一下，刚开始以为是网络的问题，结果发现不是，我开了 VPN 也是报这个错，后来以为是某个依赖的问题，我换了好几个远程依赖都不行，劳烦大佬看看，挺喜欢咱们这个插件的，希望大佬抽空看看

```
出错了
查找依赖库历史版本时出错！
若不能通过以下log分析到具体原因 如出现UnknownHostException、 SocketTimeoutException等Exception， 请检查网络是否正常）请复制以下log到 https://github.com/wuyr/GoogleLibraryVersionQuerier 上提issue:

java.net.SocketTimeoutException: Read timed out 
at java.base/java.net.SocketlnputStream.socketRead0(Native Method)
at java.base/java.net.SocketlnputStreamsocketRead(SocketlnputStream.java:1 15)
at javabase/java.net.SocketlnputStream.read(SocketlnputStream.java:168)
at java.base/java.net.SocketlnputStreamread(SocketInputStream.java:140) 
at java.base/sun.security.ssl.SSLSocketInputRecord read(SSLSocketlnputRecord.java:478)
at java.base/sun.security.ssl SSLSocketInputRecord.read Header(SSLSocketInputRecord.java:472)
at java.base/sun.security.ssl. SSLSocketlnputReco rd.decode(SSLSocketlnputRecord.java: 160)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
at java.base/sun.security.ssl.SSLSocketlmpl.decode(SSLSocketlmpl.java:1418)
at java.base/sun.security.sslSSLSocketlmpl.readHandshakeRecord(SSLSocketImpljava:1324)
at java.base/sun.security.sslSSLSocketlmpl. startHandshake(SSLSocketlmpl.java:440)
at java.base/sun.security.ssl.SSLSocketlmpl. startHandshake(SSLSocketlmpl.java:411)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
at java.base/sun.net.www.protocol.https AbstractDelegateHttps URLConnection.connect(AbstractDelegateHttpsURLConnection. java:197)
at java.base/sun.net.www.protoco.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
at java.base/sun.net.www.protocol.https HttpsURLConnectionmpl.getResponseCode(Https URLConnectionImpl.java:334) at com.wuyr.google_library_ query.NetworkRequstterKt.getAPIResponse(NetworkRequstter.kt:140)
at com.wuyr.google_lbrary_query.NetworkRequstterKt.getAvailableVersions(NetworkRequstter.kt:185)
at com.wuyr.google_library_ query.QueryAction$actionPerformed$1.invoke(QueryAction.kt:113)
at com.wuyr.google_ library_query.QueryAction $actionPerformed$1.invoke(QueryAction.kt:24)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) 
```

**Comment by 880634** [comment]
现在又可以了，不知道为何，issue 先关闭了。
